[project]
name = "drf-ecommerce"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-extensions>=4.1",
    "djangorestframework>=3.16.0",
    "pillow>=11.2.1",
]
